(("name" . "clos")
("version" . "0.1.0")
("description" . "Common Lisp Object System port to Scheme")
("keywords")
("author" 
    (""))
("private" . #f)
("scripts")
("dependencies")
("devDependencies"))
